export const COMPANY_REPOSITORY = 'COMPANY_REPOSITORY';
export const CREATE_COMPANY = 'CREATE_COMPANY';
export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES';
export const GET_COMPANY_BY_ID = 'GET_COMPANY_BY_ID';
